BankSystem/Models/BankAccount.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BankSystem.Models
{
    public class BankAccount
    {
        public BankAccount()
        {
            BankCards = new List<BankCard>();
            SentTransactions = new List<Transaction>();
            RecievedTransactions = new List<Transaction>();
        }
        [Key]
        public int ID { get; set; }
        public string Nr { get; set; }
        public long OpenTimestamp { get; set; }
        public double Balance { get; set; }
        public double MonthlyTariff { get; set; }
        public BankAccountStatus BankAccountStatus { get; set; }
        public bool InDebt { get; set; }

        public int ClientID { get; set; }
        [Required]
        public virtual Client Client { get; set; }
        public virtual ICollection<BankCard> BankCards { get; set; }
        public virtual ICollection<Transaction> SentTransactions { get; set; }
        public virtual ICollection<Transaction> RecievedTransactions { get; set; }
    }
    public enum BankAccountStatus
    {
        blocked,
        closed,
        active
    }
}

BankSystem/Controllers/BankAccountController.cs
using BankSystem.Models;
using BankSystem.Repositories;
using BankSystem.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace BankSystem.Controllers
{
    public class BankAccountController : Controller
    {
        private readonly Repository _repository;
        private readonly UserManager<User> _userManager;

        public BankAccountController(Repository repository, UserManager<User> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            if (User.IsInRole("Admin"))
                return RedirectToAction("GetAllAccounts");
            else
                return RedirectToAction("GetMyAccounts");
        }

        [Authorize(Roles = "Client")]
        public IActionResult GetMyAccounts()
        {
            Console.WriteLine();
            List<CurrentAccount> currentBankAccounts = _repository.CurrentAccounts.Where(x => x.ClientID == _userManager.GetUserAsync(User).Result.Client.ID).ToList();
            List<SavingsAccount> savingsBankAccounts = _repository.SavingsAccounts.Where(x => x.ClientID == _userManager.GetUserAsync(User).Result.Client.ID).ToList();
            List<PensionAccount> pensionBankAccounts = _repository.PensionAccounts.Where(x => x.ClientID == _userManager.GetUserAsync(User).Result.Client.ID).ToList();
            BankAccountList allBankAccounts = new BankAccountList()
            {
                allCurrentAccounts = currentBankAccounts,
                allPensionAccounts = pensionBankAccounts,
                allSavingsAccounts = savingsBankAccounts

            };
            
            return View("/Views/BankAccount/UserAccountView.cshtml", allBankAccounts);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetAllAccounts()
        {
            IEnumerable<BankAccount> bankaccs = _repository.BankAccounts;
            return View("/Views/BankAccount/AdminBankAccountsView.cshtml", bankaccs);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Activate(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _repository.BankAccounts.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            obj.BankAccountStatus = BankAccountStatus.active;
            _repository.SaveChanges();
            return RedirectToAction("/Views/BankAccount/AdminBankAccountsView.cshtml");
        }

        [Authorize(Roles = "Client")]
        public IActionResult AddAccountIndex()
        {
            return View();
        }

        public IActionResult RegisterAccount(string? accountType, string? pillarType)
        {
            string GenerateBankNumber()
            {
                string bankNumber = null;
                var bankAccounts = _repository.BankAccounts;
                Random random = new Random();
                bankNumber += "LT";
                bankNumber += "01";
                bankNumber += "99999";
                bankNumber += random.Next(100000, 999999).ToString();
                bankNumber += random.Next(10000, 99999).ToString();

                foreach (var bankAccount in bankAccounts)
                {
                    if (bankNumber == bankAccount.Nr)
                    {
                        bankNumber = "";
                        bankNumber += "LT";
                        bankNumber += "01";
                        bankNumber += "99999";
                        bankNumber += random.Next(100000, 999999).ToString();
                        bankNumber += random.Next(10000, 99999).ToString();
                    }
                }
                return bankNumber;
            }

            if (accountType == "currentAccount")
            {
                CurrentAccount currentAccount = new CurrentAccount()
                {
                    TransactionTariff = 0.30,
                    Overdraft = 500,
                    Interest = 0.00,
                    Nr = GenerateBankNumber(),            
                    OpenTimestamp = DateTime.Today.Ticks,
                    Balance = 0,
                    MonthlyTariff = 2.70,
                    BankAccountStatus = BankAccountStatus.blocked,
                    InDebt = false,
                    Client = _userManager.GetUserAsync(User).Result.Client
                };
                _repository.CurrentAccounts.Add(currentAccount);
                _repository.SaveChanges();
            }
            else if (accountType == "savingsAccount")
            {
                SavingsAccount savingsAccount = new SavingsAccount()
                {
                    TransferAmount = 50,
                    TransferDay = 5,
                    Interest = 0.04,
                    Nr = GenerateBankNumber(),
                    OpenTimestamp = DateTime.Today.Ticks,
                    Balance = 0,
                    MonthlyTariff = 0.50,
                    BankAccountStatus = BankAccountStatus.blocked,
                    InDebt = false,
                    Client = _userManager.GetUserAsync(User).Result.Client
                };
                _repository.SavingsAccounts.Add(savingsAccount);
                _repository.SaveChanges();
            }

            else if (accountType == "pensionAccount")
            {
                if (pillarType == "first_pillar")
                {
                    PensionAccount pensionAccount = new PensionAccount()
                    {
                        TransferAmount = 20,
                        TransferDay = 5,
                        Tier = new Tier()
                        {
                            TierType = TierType.first_pillar,
                            Percent = 1.5

                        },
                        Nr = GenerateBankNumber(),     
                        OpenTimestamp = DateTime.Today.Ticks,
                        Balance = 0,
                        MonthlyTariff = 0,
                        BankAccountStatus = BankAccountStatus.blocked,
                        InDebt = false,
                        Client = _userManager.GetUserAsync(User).Result.Client
                    };
                    _repository.PensionAccounts.Add(pensionAccount);
                    _repository.SaveChanges();
                }
                else if (pillarType == "second_pillar")
                {
                    PensionAccount pensionAccount = new PensionAccount()
                    {
                        TransferAmount = 30,
                        TransferDay = 5,
                        Tier = new Tier()
                        {

                            TierType = TierType.second_pillar,
                            Percent = 3
                        },
                        Nr = GenerateBankNumber(),
                        OpenTimestamp = DateTime.Today.Ticks,
                        Balance = 0,
                        MonthlyTariff = 0,
                        BankAccountStatus = BankAccountStatus.blocked,
                        InDebt = false,
                        Client = _userManager.GetUserAsync(User).Result.Client
                    };
                    _repository.PensionAccounts.Add(pensionAccount);
                    _repository.SaveChanges();
                }

                else if (pillarType == "third_pillar")
                {
                    PensionAccount pensionAccount = new PensionAccount()
                    {
                        TransferAmount = 50,
                        TransferDay = 5,
                        Tier = new Tier()
                        {
                            TierType = TierType.third_pillar,
                            Percent = 3.5

                        },
                        Nr = GenerateBankNumber(),
                        OpenTimestamp = DateTime.Today.Ticks,
                        Balance = 0,
                        MonthlyTariff = 0,
                        BankAccountStatus = BankAccountStatus.blocked,
                        InDebt = false,
                        Client = _userManager.GetUserAsync(User).Result.Client
                    };
                    _repository.PensionAccounts.Add(pensionAccount);
                    _repository.SaveChanges();
                }


            }
            return RedirectToAction("GetMyAccounts");
        }



    }
}

BankSystem/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace BankSystem.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BankSystem/Views/BankAccount/AddAccountIndex.cshtml
@{
    ViewData["Title"] = "AddAccountIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Pridėti banko sąskaitą</h1>

<div class="align-content-center">


    <form method="post" asp-controller=BankAccount asp-action="RegisterAccount">

        <h3>Pasirinkite sąskaitos tipą:</h3>
        <div>
            <input type="radio" id="currentAccount" name="accountType" value="currentAccount">
            <label for="currentAccount">Einamoji sąskaita</label><br>
            <input type="radio" id="savingsAccount" name="accountType" value="savingsAccount">
            <label for="savingsAccount">Taupymo sąskaita</label><br>
            <input type="radio" id="pensionAccount" name="accountType" value="pensionAccount">
            <label for="pensionAccount">Pensijos sąskaita</label><br>
        </div>
        <h3>Pasirinkite pensijos sąskaitos pakopą:</h3>
        <div>
            <input type="radio" id="first_pillar" name="pillarType" value="first_pillar" disabled> Pirma pakopa<br />
            <input type="radio" id="second_pillar" name="pillarType" value="second_pillar" disabled> Antra pakopa<br />
            <input type="radio" id="third_pillar" name="pillarType" value="third_pillar" disabled> Trečia pakopa

        </div>

        <h3>Banko sąskaitos sąlygos</h3>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Mėnesinis įkainis (€)</th>
                    <th scope="col">Pervedimo įkainis (€)</th>
                    <th scope="col">Palūkanos (%)</th>
                    <th scope="col">Overdraftas (€)</th>
                    <th scope="col">Automatiško pervedimo suma (€)</th>
                    <th scope="col">Automatiško pervedimo mėnesio diena</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td id="menIkainis"></td>
                    <td id="perIkainis"></td>
                    <td id="palukanos"></td>
                    <td id="overdraftas"></td>
                    <td id="perSuma"></td>
                    <td id="perDiena"></td>
                </tr>
            </tbody>
        </table>
        <h3>Pakopos sąlygos</h3>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Pakopos tipas</th>
                    <th scope="col">Pakopos palūkanos (%)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td id="pakopTipas"></td>
                    <td id="pakopProcentas"></td>

                </tr>
            </tbody>
        </table>



        <button type="submit" id="1" class="btn btn-secondary btn-lg btn-block" disabled>Pridėti kortelę</button>
    </form>
</div>

<script>
    document.getElementById("pensionAccount").onclick = function () {
        document.getElementById("menIkainis").innerHTML = ""
        document.getElementById("perIkainis").innerHTML = ""
        document.getElementById("palukanos").innerHTML = ""
        document.getElementById("overdraftas").innerHTML = ""
        document.getElementById("perSuma").innerHTML = ""
        document.getElementById("perDiena").innerHTML = ""
        document.getElementById("pakopTipas").innerHTML = ""
        document.getElementById("pakopProcentas").innerHTML = ""
        document.getElementById("1").disabled = false;

        document.getElementById("1").disabled = true;
        document.getElementById("first_pillar").disabled = false;
        document.getElementById("first_pillar").onclick = function () {

            document.getElementById("menIkainis").innerHTML = "Negalioja"
            document.getElementById("perIkainis").innerHTML = "Negalioja"
            document.getElementById("palukanos").innerHTML = "Žiūrėti pakopos sąlygas"
            document.getElementById("overdraftas").innerHTML = "Negalioja"
            document.getElementById("perSuma").innerHTML = "20"
            document.getElementById("perDiena").innerHTML = "5"
            document.getElementById("pakopTipas").innerHTML = "Pirma pakopa"
            document.getElementById("pakopProcentas").innerHTML = "1.5"
            document.getElementById("1").disabled = false;
        }


        document.getElementById("second_pillar").disabled = false;
        document.getElementById("second_pillar").onclick = function () {
            document.getElementById("menIkainis").innerHTML = "Negalioja"
            document.getElementById("perIkainis").innerHTML = "Negalioja"
            document.getElementById("palukanos").innerHTML = "Žiūrėti pakopos sąlygas"
            document.getElementById("overdraftas").innerHTML = "Negalioja"
            document.getElementById("perSuma").innerHTML = "30"
            document.getElementById("perDiena").innerHTML = "5"
            document.getElementById("pakopTipas").innerHTML = "Antra pakopa"
            document.getElementById("pakopProcentas").innerHTML = "3"
            document.getElementById("1").disabled = false;
        }
        document.getElementById("third_pillar").disabled = false;
        document.getElementById("third_pillar").onclick = function () {
            document.getElementById("menIkainis").innerHTML = "Negalioja"
            document.getElementById("perIkainis").innerHTML = "Negalioja"
            document.getElementById("palukanos").innerHTML = "Žiūrėti pakopos sąlygas"
            document.getElementById("overdraftas").innerHTML = "Negalioja"
            document.getElementById("perSuma").innerHTML = "50"
            document.getElementById("perDiena").innerHTML = "5"
            document.getElementById("pakopTipas").innerHTML = "Trečia pakopa"
            document.getElementById("pakopProcentas").innerHTML = "3.5"
            document.getElementById("1").disabled = false;
        }
    }

    document.getElementById("savingsAccount").onclick = function () {
        document.getElementById("first_pillar").checked = false;
        document.getElementById("second_pillar").checked = false;
        document.getElementById("third_pillar").checked = false;
        document.getElementById("first_pillar").disabled = true;
        document.getElementById("second_pillar").disabled = true;
        document.getElementById("third_pillar").disabled = true;
        document.getElementById("1").disabled = false;

        document.getElementById("menIkainis").innerHTML = "0.50"
        document.getElementById("perIkainis").innerHTML = "Negalioja"
        document.getElementById("palukanos").innerHTML = "0.04"
        document.getElementById("overdraftas").innerHTML = "Negalioja"
        document.getElementById("perSuma").innerHTML = "50"
        document.getElementById("perDiena").innerHTML = "5"
        document.getElementById("pakopTipas").innerHTML = ""
        document.getElementById("pakopProcentas").innerHTML = ""
    }

    document.getElementById("currentAccount").onclick = function () {
        document.getElementById("first_pillar").checked = false;
        document.getElementById("second_pillar").checked = false;
        document.getElementById("third_pillar").checked = false;
        document.getElementById("first_pillar").disabled = true;
        document.getElementById("second_pillar").disabled = true;
        document.getElementById("third_pillar").disabled = true;
        document.getElementById("1").disabled = false;


        document.getElementById("menIkainis").innerHTML = "2.70"
        document.getElementById("perIkainis").innerHTML = "0.30"
        document.getElementById("palukanos").innerHTML = "0.00"
        document.getElementById("overdraftas").innerHTML = "500"
        document.getElementById("perSuma").innerHTML = "Negalioja"
        document.getElementById("perDiena").innerHTML = "Negalioja"
        document.getElementById("pakopTipas").innerHTML = ""
        document.getElementById("pakopProcentas").innerHTML = ""


    }

</script>

BankSystem/Views/BankAccount/AdminBankAccountsView.cshtml
@model IEnumerable<BankSystem.Models.BankAccount>

<html>
<head>

</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <h1>Banko sąskaitos</h1>
        </div>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Banko kortelės numeris</th>
                <th scope="col">Banko kortelės tipas</th>
                <th scope="col">Sąskaitos likutis</th>
                <th scope="col">Mėnesinis įkainis</th>
                <th scope="col">Statusas</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Nr</td>
                <td>@String.Format("{0:c}", @item.Balance).ToString()</td>
                <td>@String.Format("{0:c}", @item.MonthlyTariff).ToString()</td>
                @switch (item.BankAccountStatus)
                {
                    case BankAccountStatus.active:
                        <td>Aktyvi</td>
                        break;
                    case BankAccountStatus.blocked:
                        <td>Užblokuota</td>
                        break;
                    case BankAccountStatus.closed:
                        <td>Uždaryta</td>
                        break;

                }
                @if (item.BankAccountStatus == BankAccountStatus.blocked)
                {
                    <td>
                        <form method="post" asp-controller="BankAccount" asp-route-Id="@item.ID" asp-action="Activate">
                            <button type="submit" class="btn btn-success">Aktyvuoti</button>
                        </form>
                    </td>
                }
            </tr>

            }

        </tbody>
    </table>
</body>
</html>

BankSystem/Views/BankAccount/RegistrationView.cshtml
@model IEnumerable<BankSystem.Models.BankAccount>

<html>
<head>

</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <h1>Mano banko sąskaitos</h1>
        </div>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Sąskaitos likutis</th>
                <th scope="col">Mėnesinis tarifas</th>
                <th scope="col">Statusas</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Nr</td>
                    <td>@item.Balance</td>
                    <td>@item.MonthlyTariff</td>
                    <td>@item.BankAccountStatus</td>
                </tr>
            }
        </tbody>
    </table>
    <form method="post" asp-controller="BankAccount" asp-action="AddAccountIndex">
        <button type="submit" class="btn btn-secondary btn-lg btn-block">Pridėti naują banko sąskaitą</button>
    </form>
</body>
</html>

BankSystem/Views/BankAccount/UserAccountView.cshtml
@model BankSystem.ViewModel.BankAccountList

<html>
<head>

</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <h1>Mano banko sąskaitos</h1>
        </div>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Banko sąskaitos numeris</th>
                <th scope="col">Banko sąskaitos tipas</th>
                <th scope="col">Sąskaitos likutis</th>
                <th scope="col">Mėnesinis įkainis</th>
                <th scope="col">Statusas</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.allCurrentAccounts)
            {
                <tr>
                    <td>@item.Nr</td>
                    <td>Einamoji sąskaita</td>
                    <td>@String.Format("{0:c}", @item.Balance).ToString()</td>
                    <td>@String.Format("{0:c}", @item.MonthlyTariff).ToString()</td>
                    @if (item.BankAccountStatus == BankAccountStatus.active)
                    {
                        <td>Aktyvi</td>
                    }
                    else if (item.BankAccountStatus == BankAccountStatus.blocked)
                    {
                        <td>Užblokuota</td>
                    }
                    else
                    {
                        <td>Uždaryta</td>
                    }

                </tr>
            }
            @foreach (var item in Model.allPensionAccounts)
            {
        <tr>
            <td>@item.Nr</td>
            <td>Pensijos kaupimo sąskaita</td>
            <td>@String.Format("{0:c}", @item.Balance).ToString()</td>
            <td>@String.Format("{0:c}", @item.MonthlyTariff).ToString()</td>
            @if (item.BankAccountStatus == BankAccountStatus.active)
            {
                <td>Aktyvi</td>
            }
            else if (item.BankAccountStatus == BankAccountStatus.blocked)
            {
                <td>Užblokuota</td>
            }
            else
            {
                <td>Uždaryta</td>
            }

        </tr>
            }
            @foreach (var item in Model.allSavingsAccounts)
            {
        <tr>
            <td>@item.Nr</td>
            <td>Taupymo sąskaita</td>
            <td>@String.Format("{0:c}", @item.Balance).ToString()</td>
            <td>@String.Format("{0:c}", @item.MonthlyTariff).ToString()</td>
            @if (item.BankAccountStatus == BankAccountStatus.active)
            {
                <td>Aktyvi</td>
            }
            else if (item.BankAccountStatus == BankAccountStatus.blocked)
            {
                <td>Užblokuota</td>
            }
            else
            {
                <td>Uždaryta</td>
            }

        </tr>
            }
        </tbody>
    </table>
    <form method="post" asp-controller="BankAccount" asp-action="AddAccountIndex">
        <button type="submit" id="randomButton" class="btn btn-secondary btn-lg btn-block">Pridėti naują banko sąskaitą</button>
    </form>
</body>
</html>