BankSystem/Models/BankCard.cs
using System.ComponentModel.DataAnnotations;

namespace BankSystem.Models
{
    public class BankCard
    {
        [Key]
        public int ID { get; set; }
        public string Nr { get; set; }
        public long ExpirationTimestamp { get; set; }
        public string Cvc { get; set; }
        public bool Contactless { get; set; }
        public bool IsActive { get; set; }

        public int BankCardTypeID { get; set; }
        [Required]
        public virtual BankCardType BankCardType { get; set; }
        public int BankAccountID { get; set; }
        [Required]
        public virtual BankAccount BankAccount { get; set; }
    }
}

BankSystem/Models/BankCardType.cs
using System.Collections.Generic;

namespace BankSystem.Models
{
    public class BankCardType
    {
        public BankCardType()
        {
            BankCards = new List<BankCard>();
        }
        public int ID { get; set; }
        public CardType CardType { get; set; }
        public double Tariff { get; set; }
        public double Limit { get; set; }
        public Organization Organization { get; set; }
        public bool IsInsured { get; set; }

        public virtual ICollection<BankCard> BankCards { get; set; }
    }
    public enum CardType
    {
        silver,
        standard,
        golden,
        platinum,
        black
    }
    public enum Organization
    {
        visa,
        mastercard
    }
}

BankSystem/Controllers/BankCardsController.cs
using BankSystem.Models;
using BankSystem.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace BankSystem.Controllers
{
    [Authorize]
    public class BankCardsController : Controller
    {
        private readonly Repository _repository;
        private readonly UserManager<User> _userManager;

        public BankCardsController(Repository repository, UserManager<User> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        [Authorize(Roles = "Client")]
        public IActionResult Index()
        {
            IEnumerable<BankCard> bank = GetCurrentUserBankCards();
            return View(bank);
        }

        [Authorize(Roles = "Client")]
        public IActionResult Deactivate(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _repository.BankCards.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            obj.IsActive = false;
            _repository.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Client")]
        public IActionResult AddCard()
        {
            IEnumerable<BankAccount> bankacc = GetCurrentUserBankAccounts();
            return View(bankacc);
        }

        private IEnumerable<BankCard> GetCurrentUserBankCards()
        {
            return _repository.BankCards.Where(x => x.BankAccount.ClientID == _userManager.GetUserAsync(User).Result.Client.ID);
        }

        private IEnumerable<BankAccount> GetCurrentUserBankAccounts()
        {
            return _repository.BankAccounts.Where(x => x.ClientID == _userManager.GetUserAsync(User).Result.Client.ID);
        }

        [Authorize(Roles = "Client")]
        public IActionResult SendAdditionRequest(string? cardType, string? contactless, string? bankAcc)
        {
            bool contact = false;
            if (cardType == "Taip")
                contact = true;

            var baseDate = new DateTime(1970, 01, 01);
            var toDate = DateTime.Today;
            var expirationDate = Convert.ToInt64(toDate.AddYears(3).Subtract(baseDate).TotalSeconds);

            BankAccount bankAccount = _repository.BankAccounts.Where(x => x.Nr == bankAcc).FirstOrDefault();

            if (Enum.TryParse(cardType, out CardType cardTypeEnum))
            {
                BankCard bankCard = new BankCard
                {
                    IsActive = true,
                    Nr = Guid.NewGuid().ToString(),
                    Contactless = contact,
                    BankAccount = bankAccount,
                    BankCardType = new BankCardType { CardType = cardTypeEnum },
                    Cvc = "597",
                    ExpirationTimestamp = expirationDate
                };
                _repository.BankCards.Add(bankCard);
                _repository.SaveChanges();
            }
            else
            {
                return NotFound(cardType);
            }

            return RedirectToAction("Index");
        }
    }
}

BankSystem/Views/BankCards/AddCard.cshtml
@model IEnumerable<BankSystem.Models.BankAccount>
@{
    ViewData["Title"] = "AddCardView";
}

<h1>Pridėti kortelę</h1>

<div class="align-content-center">
    @{ if (Model.Count() == 0)
        {
            <h3>Nėra aktyvios banko sąskaitos</h3>
        }
        else
        {
            <h3>Pasirinkite banko sąskaitą:</h3>
            <form method="post" asp-controller=BankCards asp-action="SendAdditionRequest">
                @foreach (var item in Model)
                {
                    <input type="radio" name="bankAcc" value="@item.Nr" />
                    <label>@item.Nr</label>
                    <br />
                }


                <h3>Ar norima bekontaktės kortelės?</h3>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="contacless" value="True">
                    <label>Taip</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="contacless" value="False">
                    <label>Ne</label>
                </div>

                <h3>Pasirinkite kortelės tipą</h3>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cardType" value="standard">
                    <label>Standartinė</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cardType" value="silver">
                    <label>Sidabrinė</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cardType" value="golden">
                    <label>Auksinė</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cardType" value="platinum">
                    <label>Platininė</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cardType" value="black">
                    <label>Juoda</label>
                </div>


                <button type="submit" class="btn btn-secondary btn-lg btn-block">Pridėti kortelę</button>
            </form>
        }
    }
</div>

BankSystem/Views/BankCards/Index.cshtml
@model IEnumerable<BankSystem.Models.BankCard>

<html>
<head>

</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <h1>Mano kortelės</h1>
        </div>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Nr</th>
                <th scope="col">Statusas</th>
                <th scope="col">Kortelės tipas</th>
                <th scope="col">Balansas</th>
                <th scope="col">Skola</th>
                <th scope="col">Veiksmas</th>
            </tr>
        </thead>
        <tbody>
            @{int i = 0;}
            @foreach (var item in Model)
            {
            <tr>
                @{i += 1;}
                <th scope="row">@i</th>
                <td>@item.ID</td>
                <td>@item.Nr</td>
                <td>@(item.IsActive ? "Aktyvi" : "Neaktyvi")</td>

                @if (item.BankCardType.CardType == CardType.silver)
                {
                    <td>Sidabrinė</td>
                }
                @if (item.BankCardType.CardType == CardType.standard)
                {
                    <td>Standartinė</td>
                }
                @if (item.BankCardType.CardType == CardType.golden)
                {
                    <td>Auksinė</td>
                }
                @if (item.BankCardType.CardType == CardType.platinum)
                {
                    <td>Platininė</td>
                }
                @if (item.BankCardType.CardType == CardType.black)
                {
                    <td>Juoda</td>
                }
                <td>@item.BankAccount.Balance</td>
                <td>@(item.BankAccount.InDebt ? "Yra" : "Nėra")</td>
                <td>
                    <form method="post" asp-controller="BankCards" asp-route-Id="@item.ID" asp-action="Deactivate">
                        <button type="submit" id="@item.Nr" class="btn btn-danger">Deaktyvuoti</button>
                    </form>
                </td>
            </tr>
                @if (!item.IsActive)
                {
                    <script>

                        document.getElementById("@item.Nr").style.display = 'none';

                    </script>
                }

            }
        </tbody>
    </table>
    <form method="post" asp-controller="BankCards" asp-action="AddCard">
        <button type="submit" class="btn btn-secondary btn-lg btn-block">Pridėti naują kortelę</button>
    </form>
</body>
</html>